### ISSUE TITLE
Change color of main nav bar

### ISSUE THREAD

**Issue by tolomaps** [kkowalsky/yourbodynotyourchoice#107]
When I showed this to Tanya and a couple of other people in the Cart Lab, they didn't even notice our main nav bar at the top, presumably because it's gray and blends in with the web browser. They suggested making that purple and making the jumbotron gray.

**Comment by kkowalsky** [comment]
the css for the navbar is pretty confusing so when it comes to editing, i'll do it. Perhaps we should wait to change it and have that as a choice in the google form?

**Comment by tolomaps** [comment]
Gotcha. Maybe let's take a look at this together once we're all in town.
I think we should at least make a branch of the website to see how it would look in a different color. It makes sense to me that it might be confusing.
