### ISSUE TITLE
make google form for website

### ISSUE THREAD

**Issue by kkowalsky** [kkowalsky/yourbodynotyourchoice#112]

**Comment by tolomaps** [comment]
@kkowalsky @DylanMoriarty: Alright I have a draft ready for y'all to look at when you get a chance. It's in our google docs folder: https://docs.google.com/forms/d/1_uE4iFs3oz12cA2cUVV-lRH47-hy6WcRhY14DABMng4/edit

**Comment by kkowalsky** [comment]
great work. I definitely think this what i was thinking.
