### ISSUE TITLE
Display all boxes on Timeline

### ISSUE THREAD

**Issue by DylanMoriarty** [kkowalsky/yourbodynotyourchoice#99]
The issue here is that while all the years are showing up, it isn't drawing 1973. This is because the function currently only draws a box when it sees that the data is different in the given year compared to the present year. 

So to fix this, we'll just need to add a new column to all the CSV's that gives '73 something to be compared to. Should be a quick fix*. 

(*he says, foolishly)

**Comment by tolomaps** [comment]
@DylanMoriarty @kkowalsky: Do we still want to do this? Or can I close the issue?

**Comment by kkowalsky** [comment]
I really want this fixed. It doesn't make sense to not have it shown on the graph, you know?

**Comment by tolomaps** [comment]
The only thing is that we'd have to verify the pre-1973 data and check to see which laws changed in 1973

**Comment by kkowalsky** [comment]
I think it's worth it... Otherwise when I build the functionality to have yearExpressed be highlight for the graph axis, it won't work as well because there's one less year for the graph than on the map.
